@echo off
setlocal EnableExtensions EnableDelayedExpansion
title Universal Backup Installer (RAR + optional SQL)

REM ===== kleine Helpers =====
set "HERE=%~dp0"
if "%HERE:~-1%"=="\" set "HERE=%HERE:~0,-1%"

echo:
echo === Universal Backup Installer ===
echo (Leere Eingabe = Standardwert)
echo:

REM ===== Eingaben =====
set /p SOURCE=📁 Quellordner (z.B. C:\FiveM - Server\Riveria Online): 
if not defined SOURCE (
  echo [FEHLER] Quellordner ist Pflicht.
  exit /b 1
)

set /p BACKUP_DIR=💾 Backup-Zielordner (Standard: C:\Backups\%~n1): 
if not defined BACKUP_DIR set "BACKUP_DIR=C:\Backups\%~n1"
if not exist "%BACKUP_DIR%" mkdir "%BACKUP_DIR%"

set /p RAR_EXE=📦 Pfad zu rar.exe (Standard: C:\Program Files\WinRAR\rar.exe): 
if not defined RAR_EXE set "RAR_EXE=C:\Program Files\WinRAR\rar.exe"

set /p RETENTION_DAYS=🧹 Aufbewahrungstage (Standard: 7): 
if not defined RETENTION_DAYS set "RETENTION_DAYS=7"

echo:
set /p INC_SQL=🗄️  Gibt es eine Datenbank, die gesichert werden soll? (Y/N, Standard: Y): 
if /I not "%INC_SQL%"=="N" ( set "INC_SQL=Y" ) else ( set "INC_SQL=N" )

set "MYSQL_BIN=" & set "MYSQL_CLI=" & set "DB_NAME=" & set "DB_USER=" & set "DB_PASS=" & set "DB_EXISTS="
if /I "%INC_SQL%"=="Y" (
  echo:
  echo === DB-Daten (XAMPP-Standard: C:\xampp\mysql\bin) ===
  set /p MYSQL_BIN=🛠️  Pfad zu mysqldump.exe (Standard: C:\xampp\mysql\bin\mysqldump.exe): 
  if not defined MYSQL_BIN set "MYSQL_BIN=C:\xampp\mysql\bin\mysqldump.exe"
  set /p MYSQL_CLI=🛠️  Pfad zu mysql.exe     (Standard: C:\xampp\mysql\bin\mysql.exe): 
  if not defined MYSQL_CLI set "MYSQL_CLI=C:\xampp\mysql\bin\mysql.exe"
  set /p DB_NAME=📚  Datenbankname (z.B. riveria_online): 
  set /p DB_USER=👤  DB-User (Standard: root): 
  if not defined DB_USER set "DB_USER=root"
  set /p DB_PASS=🔑  DB-Passwort (leer lassen, wenn keins):
)

set "DEFAULT_TIME=03:15"
echo:
set /p RUN_TIME=⏰ Tägliche Uhrzeit HH:MM (Standard: %DEFAULT_TIME%): 
if not defined RUN_TIME set "RUN_TIME=%DEFAULT_TIME%"

set /p TASK_NAME=📝 Task-Name (Standard: Universal Daily Backup): 
if not defined TASK_NAME set "TASK_NAME=Universal Daily Backup"

echo:
echo === Zusammenfassung ===
echo Quelle        : "%SOURCE%"
echo Backup-Ordner : "%BACKUP_DIR%"
echo RAR           : "%RAR_EXE%"
echo Retention     : %RETENTION_DAYS% Tage
if /I "%INC_SQL%"=="Y" (
  echo SQL-Dump     : JA
  echo   mysqldump  : "%MYSQL_BIN%"
  echo   mysql.exe  : "%MYSQL_CLI%"
  echo   DB-Name    : %DB_NAME%
  echo   DB-User    : %DB_USER%
) else (
  echo SQL-Dump     : NEIN (nur Dateien)
)
echo Uhrzeit Task  : %RUN_TIME%
echo Task-Name     : %TASK_NAME%
echo:
pause

REM ===== Checks =====
if not exist "%SOURCE%" (
  echo [ERROR] Quellordner existiert nicht.
  exit /b 2
)
if not exist "%RAR_EXE%" (
  echo [ERROR] WinRAR rar.exe nicht gefunden.
  exit /b 3
)

if /I "%INC_SQL%"=="Y" (
  if not defined DB_NAME (
    echo [WARN] Kein DB-Name angegeben -> nur Dateien werden gesichert.
    set "INC_SQL=N"
  ) else (
    if not exist "%MYSQL_BIN%" (
      echo [WARN] mysqldump.exe nicht gefunden -> nur Dateien werden gesichert.
      set "INC_SQL=N"
    ) else if not exist "%MYSQL_CLI%" (
      echo [WARN] mysql.exe nicht gefunden -> nur Dateien werden gesichert.
      set "INC_SQL=N"
    ) else (
      REM ---- DB-Existenz pruefen ----
      if defined DB_PASS (
        for /f "usebackq delims=" %%D in (`"%MYSQL_CLI%" -s -N -u %DB_USER% -p%DB_PASS% -e "SHOW DATABASES LIKE '%DB_NAME%';"`) do set "DB_EXISTS=%%D"
      ) else (
        for /f "usebackq delims=" %%D in (`"%MYSQL_CLI%" -s -N -u %DB_USER% -e "SHOW DATABASES LIKE '%DB_NAME%';"`) do set "DB_EXISTS=%%D"
      )
      if /I not "%DB_EXISTS%"=="%DB_NAME%" (
        echo [WARN] Datenbank "%DB_NAME%" existiert nicht -> nur Dateien werden gesichert.
        set "INC_SQL=N"
      ) else (
        echo [OK] Datenbank "%DB_NAME%" gefunden. SQL-Dump wird ins Archiv geschrieben.
      )
    )
  )
)

REM ===== Backup-Script erzeugen =====
set "LOG_DIR=%BACKUP_DIR%\logs"
if not exist "%LOG_DIR%" mkdir "%LOG_DIR%"

set "BACKUP_SCRIPT=%HERE%\backup-run.bat"
> "%BACKUP_SCRIPT%" (
  echo @echo off
  echo setlocal EnableExtensions EnableDelayedExpansion
  echo REM ===== Generated by Universal Installer =====
  echo set "SOURCE=%SOURCE%"
  echo set "BACKUP_DIR=%BACKUP_DIR%"
  echo set "LOG_DIR=%BACKUP_DIR%\logs"
  echo set "RETENTION_DAYS=%RETENTION_DAYS%"
  echo set "RAR_EXE=%RAR_EXE%"
  echo set "INC_SQL=%INC_SQL%"
  if /I "%INC_SQL%"=="Y" (
    echo set "MYSQL_BIN=%MYSQL_BIN%"
    echo set "MYSQL_CLI=%MYSQL_CLI%"
    echo set "DB_HOST=localhost"
    echo set "DB_USER=%DB_USER%"
    if defined DB_PASS (echo set "DB_PASS=%DB_PASS%") else (echo set "DB_PASS=")
    echo set "DB_NAME=%DB_NAME%"
  )
  echo if not exist "%%RAR_EXE%%" ^( echo [ERROR] WinRAR fehlt: "%%RAR_EXE%%" ^& exit /b 20 ^)
  echo if not exist "%%SOURCE%%"  ^( echo [ERROR] Quellordner fehlt: "%%SOURCE%%" ^& exit /b 21 ^)
  echo if not exist "%%BACKUP_DIR%%" mkdir "%%BACKUP_DIR%%"
  echo if not exist "%%LOG_DIR%%"    mkdir "%%LOG_DIR%%"
  echo for /f %%%%i in ^('powershell -NoProfile -Command "Get-Date -Format dd_MM_yyyy_HH_mm"'^) do set "DATESTAMP=%%%%i"
  echo set "ARCHIVE=%%BACKUP_DIR%%\%%DATESTAMP%%_%~n1.rar"
  echo if "%%~n1"=="" set "ARCHIVE=%%BACKUP_DIR%%\%%DATESTAMP%%_Backup.rar"
  echo set "LOGFILE=%%LOG_DIR%%\backup_%%DATESTAMP%%.log"
  echo echo ==============================================^>^> "%%LOGFILE%%"
  echo echo Start: %%DATESTAMP%% ^>^> "%%LOGFILE%%"
  echo echo Quelle: "%%SOURCE%%" ^>^> "%%LOGFILE%%"
  echo echo Archiv: "%%ARCHIVE%%" ^>^> "%%LOGFILE%%"
  echo echo ----------------------------------------------^>^> "%%LOGFILE%%"
  echo echo [INFO] Packe Ordner... ^>^> "%%LOGFILE%%"
  echo "%%RAR_EXE%%" a -r -ep1 -idq -m5 "%%ARCHIVE%%" "%%SOURCE%%" ^>^> "%%LOGFILE%%" 2^>^&1
  echo if errorlevel 1 ^( echo [ERROR] Fehler beim Packen. ^>^> "%%LOGFILE%%" ^& exit /b 30 ^) else ^( echo [OK] Ordner hinzugefuegt. ^>^> "%%LOGFILE%%" ^)
  if /I "%INC_SQL%"=="Y" (
    echo echo [INFO] SQL-Dump ins Archiv... ^>^> "%%LOGFILE%%"
    echo if defined DB_PASS ^(
    echo   "%%MYSQL_BIN%%" --routines --events --triggers -h %%DB_HOST%% -u %%DB_USER%% -p%%DB_PASS%% %%DB_NAME%% ^| "%%RAR_EXE%%" a -si"%%DB_NAME%%.sql" "%%ARCHIVE%%" ^>^> "%%LOGFILE%%" 2^>^&1
    echo ^) else ^(
    echo   "%%MYSQL_BIN%%" --routines --events --triggers -h %%DB_HOST%% -u %%DB_USER%% %%DB_NAME%% ^| "%%RAR_EXE%%" a -si"%%DB_NAME%%.sql" "%%ARCHIVE%%" ^>^> "%%LOGFILE%%" 2^>^&1
    echo ^)
    echo if errorlevel 1 ^( echo [WARN] SQL-Dump fehlgeschlagen. ^>^> "%%LOGFILE%%" ^) else ^( echo [OK] SQL im Archiv. ^>^> "%%LOGFILE%%" ^)
  )
  echo echo [INFO] Loesche RARs aelter als %%RETENTION_DAYS%% Tage... ^>^> "%%LOGFILE%%"
  echo forfiles /p "%%BACKUP_DIR%%" /m *.rar /d -%%RETENTION_DAYS%% /c "cmd /c del /q @path" ^>^> "%%LOGFILE%%" 2^>^&1
  echo echo [DONE] Backup fertig: "%%ARCHIVE%%" ^>^> "%%LOGFILE%%"
  echo exit /b 0
)

echo [OK] Backup-Script erzeugt: "%BACKUP_SCRIPT%"

REM ===== Task einrichten =====
echo:
echo [INFO] Lege geplante Aufgabe an: "%TASK_NAME%" um %RUN_TIME% ...
schtasks /Query /TN "%TASK_NAME%" >nul 2>&1 && schtasks /Delete /TN "%TASK_NAME%" /F >nul
schtasks /Create /SC DAILY /ST %RUN_TIME% /RU "SYSTEM" /RL HIGHEST /TN "%TASK_NAME%" /TR "cmd /c \"\"%BACKUP_SCRIPT%\" \"%~n0\"\"" >nul
if errorlevel 1 (
  echo [ERROR] Aufgabe konnte nicht erstellt werden. Bitte als Administrator ausfuehren.
  exit /b 6
)
echo [OK] Aufgabe erstellt.

echo:
set /p RUNNOW=Jetzt gleich testen? (Y/N, Standard: Y): 
if /I not "%RUNNOW%"=="N" set "RUNNOW=Y"
if /I "%RUNNOW%"=="Y" (
  schtasks /Run /TN "%TASK_NAME%" >nul
  echo [INFO] Task gestartet. Pruefe "%BACKUP_DIR%" und "%BACKUP_DIR%\logs".
)

echo:
echo Fertig. Das taegliche Backup laeuft ab jetzt automatisch.
exit /b 0
